name: sanationes
description: A Dart package for all platforms to make some validations in native data types.
version: 0.0.1
repository: https://github.com/LeonardoRosaa/sanationes

environment:
  sdk: '>=2.16.1 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  equatable: ^2.0.3
